 		<div class="search">
     		<?php echo $this->pesquisa ;?>
        </div>
        <p>&nbsp;</p>
        <p><strong>Acompanhe também </strong><br /> 
        	<br>
        </p>
        <div style="">
	        <a href="#"><img src="/public/images/geral/rss_1.gif" alt="rss_1" width="32" height="32" border="0" /></a>  &nbsp;&nbsp;
	        <a href="#"><img src="/public/images/home/facebook_in.png" alt="rss_1" width="32" height="32" border="0" /></a> &nbsp;&nbsp;
	        <a href="#"><img src="/public/images/geral/rss_3.gif" alt="rss_1" width=/public//public/images/geral/geral/ight="32" border="0" /></a> &nbsp;&nbsp;
	        <a href="#"><img src="/public/images/geral/rss_4.gif" alt="rss_1" width="32" height="32" border="0" /></a>&nbsp;&nbsp;
       </div>
        <div class="bg"></div>
      	<?php echo $this->ultimas ;?>
        <p>&nbsp;</p>
        <p>&nbsp;</p>