     
        <div class="block"> <img src="/public/images/geral/img_1.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_2.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_3.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_4.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
