      <div class="left">
        <h2>Bem Vindo ao Mais Solidario<br />
          <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </span></h2>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium mque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo ullamco laboris nisi ut aliquip ex ea commodo consequat. <a href="#">read more »</a></p>
        <h2>Featured List<br />
          <span> Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span></h2>
        <div class="block"> <img src="/public/images/geral/img_1.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_2.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_3.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
        <div class="block"> <img src="/public/images/geral/img_4.gif" alt="img" width="46" height="44" class="floated" />
          <p><strong>Fusce vehicula dignissim ligula. </strong>Vestibulum sit amet neque eu neque suscipit consequat quis vel risus. </p>
          <p><a href="#"><strong>continue reading »</strong></a></p>
        </div>
      </div>
      <div class="right">
        <div class="search">
          <form id="form1" name="form1" method="post" action="">
            <label><span>
              <input name="q" type="text" class="keywords" id="textfield" maxlength="50" value="Search..." />
              </span>
              <input name="b" type="image" src="/public/images/geral/search.gif" class="button" />
            </label>
          </form>
          <div class="clr"></div>
        </div>
        <p>&nbsp;</p>
        <p><strong>Social Places</strong><br />
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#"><img src="/public/images/geral/rss_1.gif" alt="rss_1" width="32" height="32" border="0" /></a> <a href="#"><img src="images/rss_2.gif" alt="rss_1" width="32" height="32" border="0" /></a> <a href="#"><img src="/public/images/geral/rss_3.gif" alt="rss_1" width=/public//public/images/geral/geral/ight="32" border="0" /></a> <a href="#"><img src="/public/images/geral/rss_4.gif" alt="rss_1" width="32" height="32" border="0" /></a>
        <div class="bg"></div>
        <h2><br />
          News and Events<br />
          <span>Lorem ipsum dolor sit amet, consectetur </span></h2>
        <p><a href="#">12 Dec 2015 | 0 comments</a><br />
          <span>Duis nec porttitor lorem</span><br />
          Mauris et nisi urna nonfaucibus lacus magna. <br />
          Integer lacus ante then ante ullamcorper ut vulputate..</p>
        <p><a href="#">18 Dec 2015 | 5 comments</a><br />
          <span> Aenean interdum</span><br />
          Vestibulum ante ipsum primis into faucibus orci <br />
          luctus ultrices antene posuere.</p>
        <p><a href="#"><strong>more news »</strong></a></p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
      </div>
      <div class="clr"></div>
      
          </div>
  </div>
  <div class="clr"></div>

  </div>
  <?php 
//echo $this->hoje ;
  //  	echo $this->saldo ;
    	?>

  