      <div class="left">
        <h2>Bem Vindo ao Açâo Paralela<br />
        <span> Encontre alguem que precisa de sua ajuda , Encontre alguem que quer te ajudar.</span></h2>
   
      <!--     <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </span></h2>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium mque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo ullamco laboris nisi ut aliquip ex ea commodo consequat. <a href="#">read more »</a></p>
         -->
		<?php echo $this->esquerda; ?>
      </div>
      <div class="right">
       <?php echo $this->direita; ?>
      </div>
      <div class="clr"></div>

  <div class="clr"></div>
  <?php 
//echo $this->hoje ;
  //  	echo $this->saldo ;
    	?>

  