  <h2><br />
          O que há de novo <br />
          <span></span></h2>
   <?php if( $this->numFound > 0){?>
		<?php 	 foreach ($this->ultimosResultados as $ajuda){ ?>
				<p>
					<a href="/encontre/ajuda/<?php  echo $ajuda->url;?>">
						 <?php echo   Application_Model_Util::trataData($ajuda->create_at,"portal");?>
					</a>
					<br /> 
					<span><?php echo $ajuda->titulo;?></span>
					<br /> 
					<?php echo Application_Model_Util::cortaString($ajuda->descricao, 100); ?>
				</p>
		<?php }?>
	<?php } else {?>
			<p>
				<a href="<?php echo $this->url($this->url, '', true); ?>">Nova ajuda	</a>
			<p>
	<?php }?>
	