<br /><br />
<div id="view-content" style="margin-left: auto; margin-right: auto; width: 40%;">
<button name="cadastrar" id="cadastrar" type="button" class="buttonQuadradoVerde" onclick="window.location=&quot;/cadastro&quot;">cadastrar</button>
<button name="cadastrar" id="logar" type="button" class="buttonQuadrado" onclick="window.location=&quot;/auth/login&quot;">logar</button>
<br /><br />
</div>