<div class="abasPerfil">
	<div id="tabs">
		<?=$this->menu("/menu_perfil_profissional");?>
		<div id="tabs-1">
			<h3 class="titile_form">Imagem </h3>
			<div id="view-content" style="margin-left: auto;margin-right: auto;width: 190px;">
				<div  style="width: 95px; height: 90px; background-color: #FCFCFC; overflow: hidden; padding: 5px;">
					<img width="90" src="<?php echo $this->baseUrl($this->path."".$this->nome)?>" alt="Alt da imagem" />
				</div>
			</div>
				<?php echo $this->form; ?>
			<br>
			<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>	
	</div>
	</div>
</div>

