
<div id="view-content" style="margin: 20px;"  >
<h2>Bem-vindo  ->
<?php 		//if profissional 
			if(isset($this->uri) ){
				echo '<a href="'.$this->uri.' ">';
				echo "Continuaar";
				echo "</a>";
			}
			else if($this->usuario->getTipo() == 1){
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'ong', 'module' => 'default'), '', true).' ">';
				echo "Continuaar";
				echo "</a>";
			}
			else{
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'profissional', 'module' => 'default'), '', true).' ">';
				echo "Continuaar";
				echo "</a>";
			 }?>

</h2>
<p >
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type s

</p>
</div>
