<div class="abasPerfil">
	<div id="tabs">
		<?=$this->menu("/menu_perfil_profissional");?>
		<div id="tabs-1">
			<h3 class="titile_form">Mensagem</h3>
				<div id="view-content" style="margin-left: auto;margin-right: auto;width: 800px;">
					<table>
						<tr>
							<td>	<img width="50" src="<?php echo $this->baseUrl('public/images/geral/ela.jpg')?>" alt="Alt da imagem" />	</td>
							<td width="730">
								<table>
									<tr>
										<td width="50" ><strong> Admin </strong></td>
										<td>  Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus template.</td>
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td style="font-size: 10px;"><i> Menssagem emviada: a <?php echo $this->timeSince("2012-04-04 17:00:00");?>	</i></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr style="background-color:#F1F9F0;">
							<td>	<img width="50" src="<?php echo $this->baseUrl('public/images/geral/ele.jpg')?>" alt="Alt da imagem" />	</td>
							<td width="500">
								<table>
									<tr>
										<td width="50" ><strong> Eu </strong></td>
										<td>  Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus template.</td>
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td style="font-size: 10px;"><i> Menssagem emviada: a <?php echo $this->timeSince("2012-04-04 17:00:00");?>	</i></td>
									</tr>
								</table>	</tr>
					</table>
				</div>
	</div>
	</div>
</div>
