
<h3>Mensagens</h3>
<div id="view-content" style="margin-left: 50px;">
	<table>
		<tr>
			<td>	<img width="50" src="<?php echo $this->baseUrl('public/images/geral/ela.jpg')?>" alt="Alt da imagem" />	</td>
			<td width="500">&nbsp;<b> Admin </b>&nbsp;&nbsp; Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus template. 
				<br>
				Menssagem emviada: a <?php echo $this->timeSince("2012-04-04 17:00:00");?>			
			</td>
		</tr>
		<tr style="background-color:#F1F9F0;">
			<td>	<img width="50" src="<?php echo $this->baseUrl('public/images/geral/ele.jpg')?>" alt="Alt da imagem" />	</td>
			<td width="500">&nbsp;<b> Eu </b>&nbsp;&nbsp; Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus template. 
			<br>
			Menssagem emviada: a <?php echo $this->timeSince("2012-04-04 20:00:00");?>			</td>
		</tr>
	</table>

</div>