<style type="text/css">

.button {
   border-top: 1px solid #96d1f8;
   background: #0095c2;
   background: -webkit-gradient(linear, left top, left bottom, from(#63ceff), to(#0095c2));
   background: -webkit-linear-gradient(top, #63ceff, #0095c2);
   background: -moz-linear-gradient(top, #63ceff, #0095c2);
   background: -ms-linear-gradient(top, #63ceff, #0095c2);
   background: -o-linear-gradient(top, #63ceff, #0095c2);
   padding: 9px 18px;
   -webkit-border-radius: 19px;
   -moz-border-radius: 19px;
   border-radius: 19px;
   -webkit-box-shadow: rgba(0,0,0,1) 0 1px 0;
   -moz-box-shadow: rgba(0,0,0,1) 0 1px 0;
   box-shadow: rgba(0,0,0,1) 0 1px 0;
   text-shadow: rgba(0,0,0,.4) 0 1px 0;
   color: white;
   font-size: 20px;
   font-family: Georgia, Serif;
   text-decoration: none;
   vertical-align: middle;
   margin-left: 40px;
   cursor: pointer;
   
   }
.button:hover {
   border-top-color: #48b6cf;
  background: -webkit-gradient(linear, left top, left bottom, from(#6FcFff), to(#0F9FcF));
   background: -webkit-linear-gradient(top, #6FcFff, #0F9FcF);
   background: -moz-linear-gradient(top, #63ceff, #0095c2);
   background: -ms-linear-gradient(top, #63ceff, #0095c2);
   background: -o-linear-gradient(top, #63ceff, #0095c2);
   color: white;
   }
.button:active {
   border-top-color: #1b435e;
   background: #1b435e;
   }
.pesquisaDiv{
	margin-top: 0px;
	padding-left:43px; 
	padding-top:15px;
	min-height: 300px; 
	background-repeat:no-repeat; 	
	background-image: url('/public/images/busca/topo1.png'); 
	position: relative;
	
}
</style>
<div id="view-content" class="pesquisaDiv" >
	<h1  style="font-size: 20px; margin-top:-3px; color:#404053;  text-align: center;"> Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar </h1>
	<div>
	<div style="float: left;	">
		<input   type="text" name="buscar" id="buscar" value="" 
			style="height: 35px;
			-webkit-border-radius: 10px;
			-moz-border-radius: 10px;
			border-radius: 10px;
			border: 3px solid #CCCCC0;
			font-size: 14px;
			font-size: 16px;
			width: 570px;
			margin-bottom: 20px; "
			placeholder=" Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar" >
	</div>
	<div style="margin-top: -5px;width: 100px;float: left;">
	 <input type="button" class="button" value="Pesquisar" id="pesquisaTermo" /> 
	</div>
	</div>
	<div style="width: 600px;" id="resultado">
		
	</div>
</div>