<div id="menu" class="menu_topo">
<ul> 
	<li>
		<a href="<?php echo $this->url(array('controller' => 'buscar', 'action' => 'profissionais', 'module' => 'default'), '', true); ?>">
			 Achar profissional
		 </a>
	 </li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'buscar', 'action' => 'ong', 'module' => 'default'), '', true); ?>">
			Achar ong
		</a>
	</li>
		
	<?php 
		if(isset($this->usuario))
		{
	?>
	<li>
		<?php //if profissional 
			if($this->usuario->getTipo() == 1){
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'ong', 'module' => 'default'), '', true).' ">';
				echo $this->usuario->getUserName();
				echo "</a>";
			}
			else{
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'profissional', 'module' => 'default'), '', true).' ">';
				echo $this->usuario->getUserName();
				echo "</a>";
			 }?>
		 </li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'module' => 'default'), '', true); ?>">
			Logout
		</a>
	</li>
	<?php
		}
	    else{
	?>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'cadastro', 'action' => 'index', 'module' => 'default'), '', true); ?>">
			Cadastre-se
		</a>
	</li>
	
	<li>
		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login', 'module' => 'default'), '', true); ?>">
	    	Login
		</a>
	</li>
	
	<?php 	}?>
</ul>
</div>