<ul> 
	<li>
		<a href="<?php echo $this->url(array('controller' => 'encontre', 'action' => 'index', 'module' => 'default'), '', true); ?>">
			 Encontre voluntários
		 </a>
	 </li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'encontre', 'action' => 'index', 'module' => 'default'), '', true); ?>">
			Encontre ong
		</a>
	</li>
	<li>
		<?php if(isset($this->usuario)){?>
			<a href="<?php echo $this->url(array('controller' => 'cadastro', 'action' => 'ajuda', 'module' => 'default'), '', true); ?>">
				Nova ajuda
			</a>
		<?php } else {?>
		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'index', 'module' => 'default' , 'redirect' => 1), '', true); ?>">
			Nova ajuda
		</a>
		<?php }?>
	</li>
	
	<?php 	if(isset($this->usuario)){ ?>
	<li>
		<?php //if profissional 
			if($this->usuario->getTipo() == 1){
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'ong', 'module' => 'default'), '', true).' ">';
				echo $this->usuario->getUserName();
				echo "</a>";
			}
			else{
				echo '<a href="'.$this->url(array('controller' => 'perfil', 'action' => 'profissional', 'module' => 'default'), '', true).' ">';
				echo $this->usuario->getUserName();
				echo "</a>";
			 }?>
		 </li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'module' => 'default'), '', true); ?>">
			Logout
		</a>
	</li>
	<?php } else{ ?>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'cadastro', 'action' => 'index', 'module' => 'default'), '', true); ?>">
			Cadastre-se
		</a>
	</li>
	
	<li>
		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login', 'module' => 'default'), '', true); ?>">
	    	Login
		</a>
	</li>
	
	<?php 	}?>
</ul>