   <div class="FBG">
 <div class="blog">
      <h2>Penssamentos</h2>
      <p><img src="/public/images/geral/test.gif" alt="test" width="23" height="20" />
        Não diga que a vitória está perdida 	&quot; <br />
       	 se é de batalhas que se vive a vida...	&quot;
       </p>
      <p><strong>Raul Seixas </strong></p>
    </div>
    <div class="blog2">
      <h2>Ajude</h2>
      <ul>
        <li><a href="#">Envontre voluntarios</a></li>
        <li><a href="#">Ajude uma ong</a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </div>
    <div class="blog2">
      <h2>Social </h2>
      <ul>
        <li><a href="#">Blog RSS</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Novidade</a></li>
      </ul>
    </div>
    <div class="blog">
      <h2 onclick="window.location.href = 'sobre-nos';" style="cursor: pointer;"> Sobre n&oacute;s</h2>
     	 <p>      Pretendemos atuar promovendo o encontro solidário entre Ong's e voluntários, <br>
     	 propondo uma solução que possibilite que essa realidade transforme nossa sociedade, através do compartilhamento de boas ações. </p>
    </div>
    <div class="clr"></div>
    </div>
	<!-- 
	<br>
		<div class="grupo">
			<big> Sobre</big>
			<ul>
				<li>Quem somos</li>
				<li>FAQ</li>
				<li>Mapa do Site</li>
			</ul>
		</div>
		<div class="grupo">
			<big>Ongs</big>
			<ul>
				<li>Como funciona</li>
				<li>Depoimentos</li>
				<li>Achar Usuário</li>
			</ul>
		</div>
		<div class="grupo">
			<big>Para Profissionais</big>
			<ul>
				<li>Projetos</li>
				<li>Achar Ongs</li>
				<li>Como Funciona</li>
			</ul>
		</div>
	<br style="clear: both;">
		<div class="" style="font-size: 8px; font-style: italic;" >Tecnologia @Nuvem</div>
		
		 -->