<div class="clr"></div>
 	  <?php if((int)$this->slide == 1){?>
      <div id="slider">
        <!-- start slideshow -->
        <div id="slideshow">
     		 <div class="slider-item"><a href="#"><img src="/public/images/geral/simple_img_1.jpg" alt="icon" width="960" height="318" border="0" /></a></div>
        	  <div class="slider-item"><a href="#"><img src="/public/images/geral/simple_img_2.jpg" alt="icon" width="960" height="318" border="0" /></a></div>
       	   <div class="slider-item"><a href="#"><img src="/public/images/geral/simple_img_3.jpg" alt="icon" width="960" height="318" border="0" /></a></div>
       </div>
        <div class="clr"></div>
      </div>
      <?php }?>
     