
<div id="view-content" class="pesquisaDiv" >
	<h1  style="font-size: 20px; margin-top:-3px; color:#404053;  text-align: center;"> Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar </h1>
	<div>
	<div style="float: left;	">
		<input   type="text" name="buscar" id="buscar" value="" class="buscar" 
			placeholder=" Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar" >
	</div>
	<div style="margin-top: -5px;width: 100px;float: left;">
	 <input type="button" class="buttonRedondo" value="Pesquisar" id="pesquisaTermo" /> 
	</div>
	</div>
	<div style="width: 600px;" id="resultado">
		
	</div>
</div>