
<div id="view-content" class="pesquisaDiv" style="position: relative;"  >
	<h1  style="font-size: 20px; margin-top:-3px; color:#404053;  text-align: center;"> Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar </h1>
	<div>
	<div style="float: left;	">
		<input   type="text" name="buscar" id="buscar" value="<?php echo $this->termo;?>" class="buscar" 
			placeholder=" Encontre alguem que precisa de sua ajuda , Encontre alguem que  quer te ajudar" >
	</div>
	<div style="margin-top: -5px;width: 100px;float: left;">
	 <input type="button" class="buttonRedondo" value="Pesquisar" id="pesquisaTermo" /> 
	</div>
	</div>
	<div style="width: 580px;  margin-top: 10px; margin-bottom: 20px;" id="resultado" >

	<div>
		Resultados encontrados: <?php echo $this->numFound; ?>
	</div>
	
		<?php  foreach ($this->result as $ajuda){ 
			//echo $ajuda->id_oportunidade;
			//echo $ajuda->url;
		?>
	
			<div style="font-size: 18px; margin-bottom: 10px; margin-top:10px; font-weight: bold;" ><a href="/encontre/ajuda/<?php  echo $ajuda->url;?>" > <?php echo $ajuda->titulo;?> </a></div>
			<div  style="font-size: 12px;"> 
				<table>
					<tr>
						<td width="50">Local: </td>
						<td width="110">	<?php echo Application_Model_Util::trataCidadeEstado( $ajuda->nome,$ajuda->sigla); ?>  </div></td>
					</tr>
					<tr>
						<td>Data:</td>
						<td> <?php echo   Application_Model_Util::trataData($ajuda->create_at,"portal");?></td>
					</tr>
				</table>
			</div>
			<div>
				<p><?php echo Application_Model_Util::cortaString($ajuda->descricao, 300); ?></p>
			 </div>
		<?php 
		}
		?>
		
		
		<br><br><br><br>

</div>
</div>