<div id="view-content">
	<h3 class="titile_form" style="margin-left: 40px;">Nova ajuda</h3>
	<div style="margin-top: -18px; margin-bottom: 10px; height: 1px; border-bottom: 1px solid #EEEEEE; width: 100%">
	</div>
	<form id="ajuda" name="ajuda" enctype="application/x-www-form-urlencoded" action="" method="post">
		<div class="zend_form">
			<dt id="titulo-label">
				<label for="titulo" class="required" >Titulo:</label>
			</dt>
	
			<div class="campo">
				<input type="text" name="titulo" id="titulo" value="" 
						 required="required"   placeholder="Titulo"
				 		 oninvalid="setCustomValidity('Preencha o titulo')"
   				 		 onchange="try{setCustomValidity('')}catch(e){}"
				 />
			</div>
			<dt id="descricao-label">
				<label for="descricao" class="required"  id="label-descricao">Descrição:</label>
			</dt>
			<div class="campo">
				<textarea  id="descricao"  name="descricao"  placeholder="Descrição " cols="30" rows="5"  required="required" ></textarea>
			</div>
			<dt id="estado-label">
				<label for="estado" class="required"  id="label-estado"  >Estado:</label>
			</dt>
			<div class="campo">
				<select name="estado" id="estado">
					<?php foreach ($this->estado as $key=>$nome){ ?>
						 <option value="<?php echo $key;?>"><?php echo $nome;?> </option>
					<?php  }?>
				</select>
			</div>
			<dt id="cidade-label">
				<label for="cidade" class="required"  id="label-cidade"  >Cidade:</label>
			</dt>
			<div class="campo">
				<select name="cidade" id="cidade">
						 <option value="0">--Escolha a cidade--</option>
				</select>
			</div>
			<dt id="submit-label">&nbsp;</dt>
			<dd id="submit-element">
				<input type="submit" name="submit" id="submitbutton" value="cadastrar"
					class="buttonQuadrado">
			</dd>
		</div>
	</form>
	<br>

</div>
