
<h3 class="titile_form" style="margin-left: 40px;">Obrigado!</h3>
<div
	style="margin-top: -18px; margin-bottom: 10px; height: 1px; border-bottom: 1px solid #EEEEEE; width: 100%">
</div>
<div class="resultAjuda">

	<table>
		<tr>
			<td valign="top" ><label for="titulo" class="required">Código:</label></td>
			<td>
				<div class="campo" id="codigo">
					<?php echo $this->id; ?>
				</div>
			</td>
		</tr>
		<tr>
			<td valign="top" ><label for="titulo" class="required">Titulo:</label></td>
			<td>
				<div>
					<?php echo $this->titulo; ?>
				</div>	
			</td>
		</tr>
		<tr>
			<td valign="top" ><label for="descricao" class="required" id="label-descricao">Descrição:</label>
			</td>
			<td>
				<div class="campo" style="width: 400px;">
					<?php echo $this->descricao; ?>
					
				</div>
			</td>
		</tr>
		<tr>
			<td valign="top" ><label for="estado" class="required" id="label-estado">Estado:</label>
			</td>
			<td>
				<div class="campo" id="newEstado">
					<?php echo $this->estado;?>
				</div>
			</td>
		</tr>
		<tr>
			<td valign="top" ><label for="cidade" class="required" id="label-cidade">Cidade:</label>
			</td>
			<td>
				<div class="campo" id="newCidade">
					<?php echo $this->cidade;?>
				</div>
			</td>
		</tr>
	</table>
	<dt id="submit-label">&nbsp;</dt>
	<dd id="submit-element">
		<input type="submit" name="submit" id="continueButton" value="continuaar"  onclick="continueClick('/perfil/minhhas-ajudas');"   class="buttonQuadradoVerde">
		<button name="novaAjuda" id="novaAjuda" type="button" class="buttonQuadrado"  onclick="continueClick('/cadastro/ajuda');" >nova ajuda</button>
	
	</dd>
</div>
<br>

