      <div class="left">
		<h1>Sobre nós</h1>
     	 <p style="font-size: 16px;">      Pretendemos atuar promovendo o encontro solidário entre Ong's e voluntários, <br>
     	 propondo uma solução que possibilite que essa realidade transforme nossa sociedade, através do compartilhamento de boas ações. </p>
  
      </div>
      <div class="right">
        <div class="search">
          <form id="form1" name="form1" method="post" action="">
            <label><span>
              <input name="q" type="text" class="keywords" id="textfield" maxlength="50" value="Search..." />
              </span>
              <input name="b" type="image" src="/public/images/geral/search.gif" class="button" />
            </label>
          </form>
          <div class="clr"></div>
        </div>
        <p>&nbsp;</p>
        <p><strong>Social Places</strong><br />
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#"><img src="/public/images/geral/rss_1.gif" alt="rss_1" width="32" height="32" border="0" /></a> <a href="#"><img src="images/rss_2.gif" alt="rss_1" width="32" height="32" border="0" /></a> <a href="#"><img src="/public/images/geral/rss_3.gif" alt="rss_1" width=/public//public/images/geral/geral/ight="32" border="0" /></a> <a href="#"><img src="/public/images/geral/rss_4.gif" alt="rss_1" width="32" height="32" border="0" /></a>
        <div class="bg"></div>
        <h2><br />
          News and Events<br />
          <span>Lorem ipsum dolor sit amet, consectetur </span></h2>
        <p><a href="#">12 Dec 2015 | 0 comments</a><br />
          <span>Duis nec porttitor lorem</span><br />
          Mauris et nisi urna nonfaucibus lacus magna. <br />
          Integer lacus ante then ante ullamcorper ut vulputate..</p>
        <p><a href="#">18 Dec 2015 | 5 comments</a><br />
          <span> Aenean interdum</span><br />
          Vestibulum ante ipsum primis into faucibus orci <br />
          luctus ultrices antene posuere.</p>
        <p><a href="#"><strong>more news »</strong></a></p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
      </div>
      <div class="clr"></div>
      
          </div>
  </div>
  <div class="clr"></div>

  </div>
  <?php 
//echo $this->hoje ;
  //  	echo $this->saldo ;
    	?>

  